<?php
/**
 * v2.2.474 — Logo branding mobile hero card/watermark refinement.
 * Keeps previous mobile hero, but makes the System card compact + more transparent,
 * restores lowercase subtle branding watermark and adds a dark breathing gap below breadcrumbs.
 */
if (!defined('ABSPATH')) { exit; }

add_action('wp_head', function () {
  if (is_admin()) { return; }
  ?>
  <style id="zp-suite-283-logo-mobile-card-watermark-refine">@media (max-width:760px){html body #zpBrandHeroMobileKat{padding-bottom:10px!important;background:#05070d!important}html body #zpBrandHeroMobileKat .zpWebHeroKat__visual{height:545px!important;min-height:545px!important;padding-bottom:10px!important;background:#05070d!important;overflow:visible!important}html body #zpBrandHeroMobileKat .zpWebHeroKat__visualStage{height:510px!important;min-height:510px!important;overflow:visible!important}html body #zpBrandHeroMobileKat .zpWebHeroKat__breadcrumbs--mobile{bottom:18px!important;padding-bottom:0!important}html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard,html body #zpBrandHeroMobileKat .zpWebHeroKat__miniCard.zpBrandHeroMobileKat__miniCard{top:342px!important;left:24px!important;width:258px!important;max-width:258px!important;min-width:0!important;height:168px!important;min-height:168px!important;max-height:168px!important;padding:14px 15px!important;box-sizing:border-box!important;border-radius:22px!important;overflow:hidden!important;background:linear-gradient(135deg,rgba(7,10,17,.58),rgba(12,28,52,.48))!important;border:1px solid rgba(255,255,255,.16)!important;-webkit-backdrop-filter:blur(14px) saturate(130%)!important;backdrop-filter:blur(14px) saturate(130%)!important;box-shadow:none!important;transform:perspective(900px) rotateY(-8deg) rotateZ(1.5deg)!important;transform-origin:center center!important}html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard .zpWebHeroKat__miniTop{margin-bottom:10px!important}html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard .zpWebHeroKat__miniTop span{font-size:9px!important;letter-spacing:.18em!important;line-height:1.1!important}html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard .zpWebHeroKat__miniTop i,html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard .zpWebHeroKat__miniTop svg{width:18px!important;height:18px!important}html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard strong{display:block!important;font-size:17px!important;line-height:1.08!important;letter-spacing:-.045em!important;margin:0 0 8px!important}html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard p{font-size:11px!important;line-height:1.34!important;margin:0!important;max-width:220px!important}html body #zpBrandHeroMobileKat .zpWebHeroKat__watermark{display:block!important;text-transform:none!important;left:-18px!important;bottom:40px!important;font-size:clamp(82px,24vw,128px)!important;line-height:.78!important;letter-spacing:-.085em!important;color:rgba(255,255,255,.025)!important;opacity:.72!important;z-index:1!important;pointer-events:none!important}html body #zpBrandHeroMobileKat .zpWebHeroKat__visual::after,html body #zpBrandHeroMobileKat .zpBrandHeroMobileKat__miniCard::after{content:none!important;display:none!important}}</style>
  <?php
}, PHP_INT_MAX);
