<?php
/**
 * v2.2.448 — final desktop image sizing tweaks.
 * - /strony-internetowe-katowice: portfolio CTA team photo 100px lower and 15% larger vs v447.
 * - Home: first showcase Apartament Piękna image 20% smaller vs v447 while staying glued to the right.
 */
if (!defined('ABSPATH')) { exit; }

function zp_suite_265_final_desktop_image_tweaks() {
  ?>
<style id="zp-suite-front-fixes-265-v448">@media (min-width:981px){html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta{--zpCtaPhotoXDesktop:-112px!important;--zpCtaPhotoYDesktop:154px!important;--zpCtaPhotoScaleDesktop:1.104!important}html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta .zpSSCard__visual,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta .zpSSCard__mock--contact{overflow:visible!important}html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta .zpSSCard__mock--contact,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta:hover .zpSSCard__mock--contact,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta.isActive .zpSSCard__mock--contact,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta.isVisible .zpSSCard__mock--contact{transform:translate3d(var(--zpCtaPhotoXDesktop),calc(var(--zpContactPhotoUpDesktop,0px) + var(--zpCtaPhotoYDesktop)),0)!important}html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta .zpSSCard__mock--contact img,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta:hover .zpSSCard__mock--contact img,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta.isActive .zpSSCard__mock--contact img,html body #zpStronyKatowice #zpPortfolioReveal .zpSSCard--portfolioCta.isVisible .zpSSCard__mock--contact img{transform:scale(var(--zpCtaPhotoScaleDesktop))!important;transform-origin:center bottom!important;object-position:center bottom!important;max-width:none!important}html body #zpShowcaseServices .zpSSCard--web .zpSSCard__mock--webLaptop,html body .zpShowcaseServices .zpSSCard--web .zpSSCard__mock--webLaptop{inset:-7% -18% -14% 12%!important;overflow:visible!important;transform:translate3d(0,var(--move,0px),0) rotate(-1deg)!important;transform-origin:right center!important}html body #zpShowcaseServices .zpSSCard--web .zpSSCard__mock--webLaptop img,html body #zpShowcaseServices .zpSSCard--web:hover .zpSSCard__mock--webLaptop img,html body #zpShowcaseServices .zpSSCard--web.isActive .zpSSCard__mock--webLaptop img,html body #zpShowcaseServices .zpSSCard--web.isVisible .zpSSCard__mock--webLaptop img,html body .zpShowcaseServices .zpSSCard--web .zpSSCard__mock--webLaptop img,html body .zpShowcaseServices .zpSSCard--web:hover .zpSSCard__mock--webLaptop img,html body .zpShowcaseServices .zpSSCard--web.isActive .zpSSCard__mock--webLaptop img,html body .zpShowcaseServices .zpSSCard--web.isVisible .zpSSCard__mock--webLaptop img{transform:scale(1.07)!important;transform-origin:right center!important;object-position:right center!important;max-width:none!important}}</style>
  <?php
}
add_action('wp_head', 'zp_suite_265_final_desktop_image_tweaks', PHP_INT_MAX);
add_action('wp_footer', 'zp_suite_265_final_desktop_image_tweaks', PHP_INT_MAX);
